### PR TITLE
momentWithComponents should consume an array rather than a list

### PR DESCRIPTION
**Pull request by adamsmasher**
the `moment` JS function doesn't know how to work with a Melange list; it currently produces an incorrect date object when given one. This PR fixes the issue by forcing users to pass an array instead.

Added a test to validate the behaviour as well.

### CODE REVIEW

**Review by jchavarri — APPROVED** [review]
Thanks! Could we add a changelog entry please?

**Comment by adamsmasher** [comment]
Sure - are we using semver/should I bump this to 1.0.0 because of an incompatible API change? Or is 0.5.0 or 0.4.1 preferred?

**Comment by jchavarri** [comment]
We are not really using semver. For the version, there are two options:

- For now there's no need to choose version, just add a new header `Unreleased` on top of `CHANGES.md` and whenever we release a new version after more changes accumulate, we'll decide
- If you want to do a release in opam with this change, I'd choose 0.4.1 or 0.5.0 (I wouldn't move to 1.0.0 as there's still a bunch of bugs as you just found out)

**Comment by adamsmasher** [comment]
Got it - I've pushed an update to `CHANGES.md`.

**Review by jchavarri — APPROVED** [review]
Thanks!

**Pull request merged**
